spring:
  # ?????? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true # Flyway ???
    # ?????? ?? ?? ?? (???)
    locations: classpath:db/migration

  # JPA ? Hibernate ??
  jpa:
    hibernate:
      # ddl-auto: ?????? ?? ? ???(???) ?? ??
      # none: ?? ??? ?? ?? (?? ?? ??)
      # create: ?? ??? ?? ? ?? ??
      # update: ??? ??? ??
      ddl-auto: none
    properties:
      hibernate:
        # MySQL 8 ??? ?? Dialect(??) ??
        dialect: org.hibernate.dialect.MySQL8Dialect

  # ?? ?? ??
  logging:
    level:
      # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
      org.hibernate.SQL: DEBUG

# ?? ? ?? ??
server:
  port: 8080

# Swagger UI ?? (Springdoc)
springdoc:
  swagger-ui:
    enabled: true
